Added support for colour maps with Scatters
GraphingLib/GraphingLib pull request #503
Opened 2024-06-12 13:48 UTC by mamar828

## PR summary
Closes issue #496.
Documentation has not been modified.

## PR checklist

- [x] Links to the related issue (#....)
- [x] Units tests have been run and/or modified and/or added
- [ ] Docstrings are complete and documentation modified
- [x] Any new dependencies have been added to pyproject.toml and requirements.txt (in docs folder)
- [x] If new files have been added, make sure they aren't excluded by .gitignore
- [x] Any new data files have been added to manifest.in

2024-06-12 15:41 UTC, Oddball777 requested changes
Solid work, thanks for the PR. A few details:

## Scatter
- In both docstrings, remove the errorbars parameter. It's not actually an init parameter, I think it used to be, and we forgot to remove it from one of the two docstrings for some reason. We'll probably add attributes to all docstrings some day and it'll go in there
- Since the markers used to be plotted with axes.errorbars and now with axes.scatter, the marker sizes in the default are interpreted to be in different units (7 in errorbars is much bigger than 7 in scatter). Would it be possible to increase the marker sizes in the style files to make the markers visually closer to what they used to be? Not sure what the ideal new size would be, you can look in the gallery on the doc website for reference to the original size

## Figure
- Interesting edge case. Would there be a way to do it based on the figure's face color instead of the style name so that it would work for all backgrounds, even for custom styles? Something like, either use black or light grey for the errorbars, whichever has the greater contrast with the figure face color. There's probably some simple algorithm out there based on RGB values to determine which has the better contrast (@yalap13 ?)

2024-06-13 14:18 UTC, mamar828 commented
Thanks for the feedback !
I found a simple algorithm for determining the best contrast for errorbars, just like you suggested, and it looks like it's working well. The other changes have also been made.

PS : Prism is objectively the best colormap.

2024-06-13 19:51 UTC, Oddball777 commented
Awesome, thanks for the changes!

2024-06-13 19:56 UTC, Oddball777 approved these changes

2024-06-14 01:08 UTC, merged