Color bar parameters, color map range and histogram orientation
GraphingLib/GraphingLib pull request #566
Opened 2024-07-26 15:35 UTC by Mykola-P

Added the color bar parameters (label, position, orientation, etc.) for `Scatter`, `Heatmap` and `Contour`. These can be specified by calling the `add_color_bar_params` method. Also, added the color map range, which can be specified with `color_map_range=(start, end)`. Added the possibility to plot a horizontal histogram with `orientation="horizontal"`. 

## PR summary

## PR checklist

- [x] Units tests have been run and/or modified and/or added
- [x] Docstrings are complete
- [N/A] Any new dependencies have been added to pyproject.toml and requirements.txt (in docs folder)
- [N/A] If new files have been added, make sure they aren't excluded by .gitignore
- [N/A] Documentation has been updated (if applicable, see [Contributing to the documentation](https://www.graphinglib.org/en/latest/contributing.html#contributing-to-the-documentation) for details on how to make changes to the documentation)
- [x] If your changes modify the API, a short release note has been added to the ``docs/release_notes/upcoming_changes`` directory following the [Guidelines for submitting a pull request](https://www.graphinglib.org/en/latest/contributing.html#guideline-for-submitting-a-pull-request).
- [N/A] Links to the related issue (#....)

2024-07-30 15:03 UTC, Oddball777 requested changes
Hi, thanks for the PR! Really useful stuff in here.

## add_color_bar_params
There's one main thing that we'd like to see changed in order to make it fit better with the GL API. In general, we tend to prefer named parameters over catch all kwargs since it makes it easier for the user (you don't have to remember the specific parameter names like you do in matplotlib). We're not against the use of kwargs, but the most commonly used keywords should be named.

So for the add_color_bar_params functions, we'd like to see something like this:

```python
def set_color_bar_params(self, position, label, **color_bar_params) -> None:
        """
        Adds

        Parameters
        ----------
        [position and label descriptions]
        **color_bar_params: Any additional keyword arguments are passed to ``plt.colorbar`` call.
        """
        self._color_bar_params = color_bar_params
        if position is not None:
               self._color_bar_params["location"] = position
        if label is not None:
               self._color_bar_params["label"] = label
```

There are a few changes here that I should explain:
- add -> set. This is just to conform to existing GL nomenclature, since "add" typically introduces new elements on the plot
- `position` and `label` arguments are added to make it faster for the user while keeping kwargs for more advanced settings. From what I understand, orientation and location are mutually exclusive, and location is more flexible, so we'll use only location. We rename it to `position` in order to fit better with the rest of the GL API. I haven't looked into whether there are more named parameters we could add that could be used regularly.

## Bug with Contour
I noticed that the color map range doesn't seem to work as expected with Contour plots. The max and min values on the color bar itself don't match what I enter as limits. Please check if you can find a quick fix for this, if not we'll just merge the changes and I'll create a separate issue for this.

Oh and, a tiny thing about the release notes, make sure the line under the title is the same length as the title itself. Just makes building the docs simpler

Thanks again for the PR!

2024-08-06 12:25 UTC, Mykola-P commented
Hi, thanks for the feedback. As you suggested, I renamed ``add_color_bar_params`` to ``set_color_bar_params`` and left ``label`` and ``position`` as optional arguments. Based on my experience, these two are the most used arguments. I also resolved the bug with ``Contour`` where the color bar limits didn't adjust to the specified color map range. Now it should work properly.

2024-08-06 13:10 UTC, Oddball777 commented
Awesome, thanks for the edits!

2024-08-06 13:18 UTC, Oddball777 approved these changes

2024-08-06 13:20 UTC, merged